//
// Generated file, do not edit! Created by nedtool 4.6 from message/messageFile.msg.
//

#ifndef _MESSAGEFILE_M_H_
#define _MESSAGEFILE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "WaveShortMessage_m.h"    
#include "Coord.h"
// }}

/**
 * Class generated from <tt>message/messageFile.msg:23</tt> by nedtool.
 * <pre>
 * packet messageFile extends WaveShortMessage
 * {
 *     int id;
 *     Coord roi;
 *     int destination;
 * }
 * </pre>
 */
class messageFile : public ::WaveShortMessage
{
  protected:
    int id_var;
    Coord roi_var;
    int destination_var;

  private:
    void copy(const messageFile& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const messageFile&);

  public:
    messageFile(const char *name=NULL, int kind=0);
    messageFile(const messageFile& other);
    virtual ~messageFile();
    messageFile& operator=(const messageFile& other);
    virtual messageFile *dup() const {return new messageFile(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual Coord& getRoi();
    virtual const Coord& getRoi() const {return const_cast<messageFile*>(this)->getRoi();}
    virtual void setRoi(const Coord& roi);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doPacking(cCommBuffer *b, messageFile& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, messageFile& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MESSAGEFILE_M_H_

